/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mesmaths_cinematique_Collisions */

#ifndef _Included_mesmaths_cinematique_Collisions
#define _Included_mesmaths_cinematique_Collisions
#ifdef __cplusplus
extern "C" {
#endif
#undef mesmaths_cinematique_Collisions_EPSILON_CHOC_BILLE
#define mesmaths_cinematique_Collisions_EPSILON_CHOC_BILLE 0.01
#undef mesmaths_cinematique_Collisions_EPSILON_CHOC_PAROI
#define mesmaths_cinematique_Collisions_EPSILON_CHOC_PAROI 0.01
#undef mesmaths_cinematique_Collisions_PAS_DE_CHOC
#define mesmaths_cinematique_Collisions_PAS_DE_CHOC 0L
#undef mesmaths_cinematique_Collisions_CHOC_DYNAMIQUE
#define mesmaths_cinematique_Collisions_CHOC_DYNAMIQUE 1L
#undef mesmaths_cinematique_Collisions_CHOC_STATIQUE
#define mesmaths_cinematique_Collisions_CHOC_STATIQUE 2L
/*
 * Class:     mesmaths_cinematique_Collisions
 * Method:    actionReactionBilleBilleAvecEffet
 * Signature: ([DDDDDDDD)V
 */
JNIEXPORT void JNICALL Java_mesmaths_cinematique_Collisions_actionReactionBilleBilleAvecEffet
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
